// Inputs of the Report Generator's definition sheet (Google Sheet
// 1oLakDXDeEINBs0B3KSkcyM1131YnuHtAKEk6l7ClT8k), moved to code on 2026-10-05 (#48, #93).
// Edit the rows here; the sheet is a frozen reference. Field meanings are documented on
// the row type in ./types.ts.
// Rows name their panel and output pages by id, so a dangling id fails `svelte-check`.
import type { PageIdType } from './pages';
import type { PanelIdType } from './panels';
import type { InputDefinitionType } from './types';

export const inputs = [
	{
		id: 'ORG-001',
		visibility: 'hidden',
		panel: 'PANEL-001',
		label: 'ID',
		path: 'org.id',
		source: 'system',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '1',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '1',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-002',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Name',
		path: 'org.name',
		source: 'prefilled',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: 'Trident Cubed',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: ['header'],
		example: 'Trident Cubed',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-003',
		visibility: null,
		panel: 'PANEL-001',
		label: 'URL',
		path: 'org.url',
		source: 'prefilled',
		type: 'string',
		input: 'url',
		options: [],
		placeholder: '',
		value: 'https://tridentcubed.com',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: 'https://tridentcubed.com',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-004',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Logo',
		path: 'org.logo',
		source: 'prefilled',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: 'https://www.tridentcubed.com/branding/logo.svg',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001'],
		outputToPageSection: ['header'],
		example: 'https://www.tridentcubed.com/branding/logo.svg',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-005',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Address Line 1',
		path: 'org.address.line1',
		source: 'prefilled',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '800 Town and Country',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: '800 Town and Country',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-006',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Address Line 2',
		path: 'org.address.line2',
		source: 'prefilled',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: 'Ste 500',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: 'Ste 500',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-007',
		visibility: null,
		panel: 'PANEL-001',
		label: 'City',
		path: 'org.address.city',
		source: 'prefilled',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: 'Houston',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: 'Houston',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-008',
		visibility: null,
		panel: 'PANEL-001',
		label: 'State',
		path: 'org.address.state',
		source: 'prefilled',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: 'TX',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: 'TX',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-009',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Zip',
		path: 'org.address.zip',
		source: 'prefilled',
		type: 'string',
		input: 'number',
		options: [],
		placeholder: '',
		value: '77024',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: '77024',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-010',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Phone',
		path: 'org.phone',
		source: 'prefilled',
		type: 'string',
		input: 'tel',
		options: [],
		placeholder: '',
		value: '+14095432725',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: '+14095432725',
		notes: '',
		reference: []
	},
	{
		id: 'ORG-011',
		visibility: null,
		panel: 'PANEL-001',
		label: 'Email',
		path: 'org.email',
		source: 'prefilled',
		type: 'string',
		input: 'email',
		options: [],
		placeholder: '',
		value: 'operations@tridentcubed.com',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: 'operations@tridentcubed.com',
		notes: '',
		reference: []
	},
	{
		id: 'TM-001',
		visibility: null,
		panel: 'PANEL-003',
		label: 'Owner',
		path: 'team.owner',
		source: 'external',
		type: 'string',
		input: 'select',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-005', 'PAGE-020'],
		outputToPageSection: [],
		example: '',
		notes: 'Select one project owner from the remote team directory sheet.',
		reference: []
	},
	{
		id: 'TM-002',
		visibility: null,
		panel: 'PANEL-003',
		label: 'Assigned',
		path: 'team.assigned',
		source: 'external',
		type: 'array',
		input: 'multiselect',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-005'],
		outputToPageSection: [],
		example: '',
		notes: 'Select one or more assigned team members from the remote team directory sheet.',
		reference: []
	},
	{
		id: 'PRJ-001',
		visibility: 'hidden',
		panel: 'PANEL-004',
		label: 'ID',
		path: 'project.id',
		source: 'system',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'PRJ-002',
		visibility: 'hidden',
		panel: 'PANEL-004',
		label: 'Project Number',
		path: 'project.number',
		source: 'derived',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001'],
		outputToPageSection: ['header'],
		example: 'SGL-2026-01-03---01',
		notes: 'The project number is a derived value from multiple data fields.',
		reference: ['CLT-003', 'PRJ-004', 'PRJ-001']
	},
	{
		id: 'PRJ-003',
		visibility: 'hidden',
		panel: 'PANEL-004',
		label: 'Dates',
		path: 'project.dates',
		source: 'derived',
		type: 'array',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: ['TIM-002']
	},
	{
		id: 'PRJ-004',
		visibility: 'hidden',
		panel: 'PANEL-004',
		label: 'Date Created',
		path: 'project.date.created',
		source: 'system',
		type: 'date',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: ['header'],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'PRJ-005',
		visibility: 'hidden',
		panel: 'PANEL-004',
		label: 'Date Modified',
		path: 'project.date.modified',
		source: 'system',
		type: 'date',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'PRJ-006',
		visibility: null,
		panel: 'PANEL-004',
		label: 'Type',
		path: 'project.type',
		source: 'user',
		type: 'enum',
		input: 'select',
		options: [
			'Cargo',
			'Warehousing',
			'Warranty',
			'Vessel Condition',
			'Draft',
			'Bunker',
			'IHM',
			'Terminal'
		],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'PRJ-007',
		visibility: null,
		panel: 'PANEL-004',
		label: 'Title',
		path: 'project.title',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'PRJ-008',
		visibility: null,
		panel: 'PANEL-004',
		label: 'Subtitle',
		path: 'project.subtitle',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-001',
		visibility: 'hidden',
		panel: 'PANEL-002',
		label: 'ID',
		path: 'client.id',
		source: 'system',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-002',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Company',
		path: 'client.company',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-003',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Short Name',
		path: 'client.shortname',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-004',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Logo',
		path: 'client.logo',
		source: 'user',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-005',
		visibility: null,
		panel: 'PANEL-002',
		label: 'URL',
		path: 'client.website',
		source: 'user',
		type: 'string',
		input: 'url',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-006',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Contact',
		path: 'client.contact',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-007',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Phone',
		path: 'client.phone',
		source: 'user',
		type: 'string',
		input: 'tel',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-008',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Email',
		path: 'client.email',
		source: 'user',
		type: 'string',
		input: 'email',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-009',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Address Line 1',
		path: 'client.address.line1',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-010',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Address Line 2',
		path: 'client.address.line2',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-011',
		visibility: null,
		panel: 'PANEL-002',
		label: 'City',
		path: 'client.address.city',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-012',
		visibility: null,
		panel: 'PANEL-002',
		label: 'State',
		path: 'client.address.state',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CLT-013',
		visibility: null,
		panel: 'PANEL-002',
		label: 'Zip',
		path: 'client.address.zip',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'FCL-001',
		visibility: 'hidden',
		panel: 'PANEL-006',
		label: 'ID',
		path: 'facility.id',
		source: 'system',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'FCL-002',
		visibility: null,
		panel: 'PANEL-006',
		label: 'Name',
		path: 'facility.name',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'FCL-003',
		visibility: null,
		panel: 'PANEL-006',
		label: 'City',
		path: 'facility.city',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'FCL-004',
		visibility: null,
		panel: 'PANEL-006',
		label: 'State',
		path: 'facility.state',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CAR-001',
		visibility: 'hidden',
		panel: 'PANEL-007',
		label: 'ID',
		path: 'carrier.id',
		source: 'system',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CAR-002',
		visibility: null,
		panel: 'PANEL-007',
		label: 'Type',
		path: 'carrier.type',
		source: 'user',
		type: 'enum',
		input: 'select',
		options: ['Sea', 'Rail', 'Air', 'Road'],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CAR-003',
		visibility: null,
		panel: 'PANEL-007',
		label: 'Name',
		path: 'carrier.name',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CAR-004',
		visibility: null,
		panel: 'PANEL-007',
		label: 'Photo',
		path: 'carrier.photo',
		source: 'user',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-003', 'PAGE-013'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CAR-005',
		visibility: null,
		panel: 'PANEL-007',
		label: 'Documents',
		path: 'carrier.documents',
		source: 'user',
		type: 'file',
		input: 'file',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-014'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'TIM-001',
		visibility: 'hidden',
		panel: 'PANEL-008',
		label: 'ID',
		path: 'timelog.id',
		source: 'system',
		type: 'string',
		input: 'hidden',
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'TIM-002',
		visibility: null,
		panel: 'PANEL-008',
		label: 'Dates',
		path: 'timelog.dates',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Repeatable date groups for the project time log.',
		reference: []
	},
	{
		id: 'TIM-003',
		visibility: null,
		panel: 'PANEL-008',
		label: 'Date',
		path: 'timelog.dates.date',
		source: 'user',
		type: 'date',
		input: 'date',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-008'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'TIM-004',
		visibility: null,
		panel: 'PANEL-008',
		label: 'Entries',
		path: 'timelog.dates.entries',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-008'],
		outputToPageSection: [],
		example: '',
		notes: 'Repeatable time entries inside each logged date.',
		reference: []
	},
	{
		id: 'TIM-005',
		visibility: null,
		panel: 'PANEL-008',
		label: 'Time',
		path: 'timelog.dates.entries.time',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: 'e.g. 08:30',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-008'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'TIM-006',
		visibility: null,
		panel: 'PANEL-008',
		label: 'Description',
		path: 'timelog.dates.entries.description',
		source: 'user',
		type: 'string',
		input: 'textarea',
		options: [],
		placeholder: '',
		value: 'Describe the activity',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-008'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'ITM-001',
		visibility: null,
		panel: 'PANEL-005',
		label: 'Title',
		path: 'items.title',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-001', 'PAGE-003'],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'ITM-002',
		visibility: null,
		panel: 'PANEL-005',
		label: 'Description',
		path: 'items.description',
		source: 'user',
		type: 'string',
		input: 'textarea',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'ITM-003',
		visibility: 'hidden',
		panel: 'PANEL-005',
		label: 'ID',
		path: 'items.item.id',
		source: 'system',
		type: 'string',
		input: null,
		options: [],
		placeholder: '',
		value: '',
		editable: false,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'ITM-004',
		visibility: null,
		panel: 'PANEL-005',
		label: 'Name',
		path: 'items.item.name',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CSTM-001',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Sections',
		path: 'custom.entries',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Repeatable custom photo sections added by the user.',
		reference: []
	},
	{
		id: 'CSTM-002',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Title',
		path: 'custom.entries.title',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CSTM-003',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Description',
		path: 'custom.entries.description',
		source: 'user',
		type: 'string',
		input: 'textarea',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CSTM-004',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Variant',
		path: 'custom.entries.variant',
		source: 'user',
		type: 'enum',
		input: 'select',
		options: ['photos-1', 'photos-2', 'photos-4', 'photos-6', 'photos-8'],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CSTM-005',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Photos',
		path: 'custom.entries.photos',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CSTM-006',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Photo',
		path: 'custom.entries.photos.photo',
		source: 'user',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: true,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'CSTM-007',
		visibility: 'conditional',
		panel: 'PANEL-012',
		label: 'Caption',
		path: 'custom.entries.photos.description',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'INSP-001',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Sections',
		path: 'inspection.groups',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Repeatable inspection sections inside the Inspection panel.',
		reference: []
	},
	{
		id: 'INSP-002',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Title',
		path: 'inspection.groups.title',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'INSP-003',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Description',
		path: 'inspection.groups.description',
		source: 'user',
		type: 'string',
		input: 'textarea',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-007', 'PAGE-009'],
		outputToPageSection: ['main'],
		example: '',
		notes: 'Inspection section description.',
		reference: []
	},
	{
		id: 'INSP-004',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Layout',
		path: 'inspection.groups.variant',
		source: 'user',
		type: 'enum',
		input: 'select',
		options: ['photos-1', 'photos-2', 'photos-4', 'photos-6', 'photos-8'],
		placeholder: '',
		value: 'photos-4',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Layout variant for the inspection section.',
		reference: []
	},
	{
		id: 'INSP-005',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Photos',
		path: 'inspection.groups.photos',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'INSP-006',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Photo',
		path: 'inspection.groups.photos.photo',
		source: 'user',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-007', 'PAGE-009'],
		outputToPageSection: ['main'],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'INSP-007',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Caption',
		path: 'inspection.groups.photos.description',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-007', 'PAGE-009'],
		outputToPageSection: ['main'],
		example: '',
		notes: '',
		reference: ['INSP-006']
	},
	{
		id: 'INSP-008',
		visibility: null,
		panel: 'PANEL-009',
		label: 'Files',
		path: 'inspection.groups.files',
		source: 'user',
		type: 'file',
		input: 'file',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-007', 'PAGE-009'],
		outputToPageSection: ['main'],
		example: '',
		notes: 'Optional file attachments for each inspection section.',
		reference: []
	},
	{
		id: 'DAM-001',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Sections',
		path: 'damages.groups',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Repeatable damage sections inside the Damages panel.',
		reference: []
	},
	{
		id: 'DAM-002',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Title',
		path: 'damages.groups.title',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'DAM-003',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Description',
		path: 'damages.groups.description',
		source: 'user',
		type: 'string',
		input: 'textarea',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-010'],
		outputToPageSection: ['main'],
		example: '',
		notes: 'Damage section description.',
		reference: []
	},
	{
		id: 'DAM-004',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Layout',
		path: 'damages.groups.variant',
		source: 'user',
		type: 'enum',
		input: 'select',
		options: ['photos-1', 'photos-2', 'photos-4', 'photos-6', 'photos-8'],
		placeholder: '',
		value: 'photos-4',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Layout variant for the damage section.',
		reference: []
	},
	{
		id: 'DAM-005',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Photos',
		path: 'damages.groups.photos',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'DAM-006',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Photo',
		path: 'damages.groups.photos.photo',
		source: 'user',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-010'],
		outputToPageSection: ['main'],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'DAM-007',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Caption',
		path: 'damages.groups.photos.description',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-010'],
		outputToPageSection: ['main'],
		example: '',
		notes: '',
		reference: ['DAM-006']
	},
	{
		id: 'DAM-008',
		visibility: null,
		panel: 'PANEL-010',
		label: 'Files',
		path: 'damages.groups.files',
		source: 'user',
		type: 'file',
		input: 'file',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-010'],
		outputToPageSection: ['main'],
		example: '',
		notes: 'Optional file attachments for each damage section.',
		reference: []
	},
	{
		id: 'DSC-001',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Sections',
		path: 'discharge.groups',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Repeatable discharge sections inside the Discharge panel.',
		reference: []
	},
	{
		id: 'DSC-002',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Title',
		path: 'discharge.groups.title',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'DSC-003',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Description',
		path: 'discharge.groups.description',
		source: 'user',
		type: 'string',
		input: 'textarea',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-019'],
		outputToPageSection: ['main'],
		example: '',
		notes: 'Discharge section description.',
		reference: []
	},
	{
		id: 'DSC-004',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Layout',
		path: 'discharge.groups.variant',
		source: 'user',
		type: 'enum',
		input: 'select',
		options: ['photos-1', 'photos-2', 'photos-4', 'photos-6', 'photos-8'],
		placeholder: '',
		value: 'photos-4',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: 'Layout variant for the discharge section.',
		reference: []
	},
	{
		id: 'DSC-005',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Photos',
		path: 'discharge.groups.photos',
		source: 'user',
		type: 'array',
		input: 'repeater',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: [],
		outputToPageSection: [],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'DSC-006',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Photo',
		path: 'discharge.groups.photos.photo',
		source: 'user',
		type: 'image',
		input: 'image',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-019'],
		outputToPageSection: ['main'],
		example: '',
		notes: '',
		reference: []
	},
	{
		id: 'DSC-007',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Caption',
		path: 'discharge.groups.photos.description',
		source: 'user',
		type: 'string',
		input: 'text',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: false,
		validation: [],
		outputToPages: ['PAGE-019'],
		outputToPageSection: ['main'],
		example: '',
		notes: '',
		reference: ['DSC-006']
	},
	{
		id: 'DSC-008',
		visibility: null,
		panel: 'PANEL-011',
		label: 'Files',
		path: 'discharge.groups.files',
		source: 'user',
		type: 'file',
		input: 'file',
		options: [],
		placeholder: '',
		value: '',
		editable: true,
		required: false,
		repeatable: true,
		validation: [],
		outputToPages: ['PAGE-019'],
		outputToPageSection: ['main'],
		example: '',
		notes: 'Optional file attachments for each discharge section.',
		reference: []
	}
] as const satisfies readonly InputDefinitionType<PanelIdType, PageIdType>[];

export type InputIdType = (typeof inputs)[number]['id'];
export type InputRowType = (typeof inputs)[number];

type ReferencedInputIdType = (typeof inputs)[number]['reference'][number];

// `reference` cannot be typed against InputIdType inside the array (the type would reference
// itself), so this line fails to compile when a reference names an input id that does not
// exist. The message does not name the id; inputs.test.ts does.
export const referencesResolve: [ReferencedInputIdType] extends [InputIdType] ? true : never = true;
