#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# github-project-sprint-board.sh
#
# Sets up GitHub Project #1 (https://github.com/users/layerdbiz/projects/1)
# as a simple Sprint board over layerdbiz/tridentcubed issues, without
# touching the Wayfinder issue system (labels, sub-issues, dependencies,
# issue bodies, branches, code).
#
# What it automates (via gh):
#   - importing every existing issue (open + closed, never PRs) into the Project
#   - verifying Status options, the Sprint board view and the built-in workflows
# What it walks you through (GitHub has no API for these):
#   - adding the "Review" option to Status
#   - creating the "Sprint" Board view grouped by Status
#   - turning on "Auto-add to project" with filter  is:issue
#   - confirming "Auto-archive items" and "Auto-close issue" stay off
#
# Safe to re-run: every step checks current state first and skips what's done.
# Needs: gh (logged in, with the 'project' scope). Works on bash 3.2+.

REPO="layerdbiz/tridentcubed"
PROJECT_OWNER="layerdbiz"
PROJECT_NUMBER=1
PROJECT_URL="https://github.com/users/${PROJECT_OWNER}/projects/${PROJECT_NUMBER}"
REQUIRED_STATUS="Todo
In Progress
Review
Done"
SPRINT_VIEW="Sprint"

# ── helpers for this wizard ────────────────────────────────────────────────

ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# count_lines: number of non-empty lines on stdin.
count_lines() { grep -c . || true; }
# join_lines SEP: joins non-empty stdin lines with SEP.
join_lines() { awk -v sep="$1" 'NF { s = s (s ? sep : "") $0 } END { print s }'; }
# has_line NEEDLE HAYSTACK: true when HAYSTACK (newline-separated) contains NEEDLE exactly.
has_line() { grep -qxF -- "$1" <<<"$2"; }

# project_graphql QUERY [--jq EXPR]: runs a GraphQL query against the project.
# The query must declare $owner: String! and $number: Int!.
project_graphql() {
  local query="$1"; shift
  gh api graphql -f query="$query" -f owner="$PROJECT_OWNER" -F number="$PROJECT_NUMBER" "$@"
}

# status_options prints the Status field's option names, one per line.
status_options() {
  gh project field-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json \
    --jq '.fields[] | select(.name == "Status") | .options[].name'
}

# missing_status_options prints required Status options that don't exist yet.
missing_status_options() {
  local have want
  have=$(status_options)
  while IFS= read -r want; do
    has_line "$want" "$have" || printf '%s\n' "$want"
  done <<<"$REQUIRED_STATUS"
}

# repo_issues prints "<number> <OPEN|CLOSED>" per issue in the repo (no PRs).
repo_issues() {
  gh issue list --repo "$REPO" --state all --limit 1000 --json number,state \
    --jq '.[] | "\(.number) \(.state)"'
}

# project_issue_numbers prints the numbers of this repo's issues already in the Project.
project_issue_numbers() {
  gh project item-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --limit 1000 --format json \
    --jq ".items[] | select(.content.type == \"Issue\" and .content.repository == \"$REPO\") | .content.number"
}

# project_pr_count prints how many pull requests are in the Project.
project_pr_count() {
  gh project item-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --limit 1000 --format json \
    --jq '[.items[] | select(.content.type == "PullRequest")] | length'
}

# sprint_view_layout prints the layout of the view named $SPRINT_VIEW, or nothing.
sprint_view_layout() {
  project_graphql '
    query($owner: String!, $number: Int!) {
      user(login: $owner) { projectV2(number: $number) {
        views(first: 50) { nodes { name layout } }
      } }
    }' --jq ".data.user.projectV2.views.nodes[] | select(.name == \"$SPRINT_VIEW\") | .layout" 2>/dev/null || true
}

# sprint_view_column_field prints the field the Sprint board's columns use, if
# the API exposes it; empty output means "couldn't tell", not "wrong".
sprint_view_column_field() {
  project_graphql '
    query($owner: String!, $number: Int!) {
      user(login: $owner) { projectV2(number: $number) {
        views(first: 50) { nodes { name
          verticalGroupByFields(first: 5) { nodes {
            ... on ProjectV2SingleSelectField { name }
            ... on ProjectV2IterationField { name }
          } }
        } }
      } }
    }' --jq ".data.user.projectV2.views.nodes[] | select(.name == \"$SPRINT_VIEW\") | .verticalGroupByFields.nodes[].name" 2>/dev/null | head -n1 || true
}

# workflow_state NAME prints "true"/"false" for a built-in workflow's enabled
# flag, or nothing if the API doesn't expose it.
workflow_state() {
  project_graphql '
    query($owner: String!, $number: Int!) {
      user(login: $owner) { projectV2(number: $number) {
        workflows(first: 50) { nodes { name enabled } }
      } }
    }' --jq ".data.user.projectV2.workflows.nodes[] | select(.name == \"$1\") | .enabled" 2>/dev/null | head -n1 || true
}

# wait_until_workflow NAME STATE: re-checks after each Enter until the built-in
# workflow reports STATE; falls back to an eyeball confirm if the API is silent.
wait_until_workflow() {
  local name="$1" want="$2" got
  while :; do
    got=$(workflow_state "$name")
    [[ "$got" == "$want" ]] && return 0
    if [[ -z "$got" ]]; then
      note "the API didn't report workflow state, so confirm by eye:"
      confirm "Is '${name}' now $([[ "$want" == true ]] && echo On || echo Off)?" && return 0
    else
      warn "'${name}' still reports enabled=${got}"
    fi
    pause "Press Enter when it's done (I'll re-check)"
  done
}

# ── stages ─────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "GitHub Project #1 · Sprint board for Trident Cubed"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Preflight: gh, auth and Project access"
say "This wizard needs the GitHub CLI logged in with the 'project' scope, and"
say "write access to ${PROJECT_URL}."
if ! command -v gh >/dev/null 2>&1; then
  fail "gh is not installed. Install it from https://cli.github.com/ and re-run."; exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  fail "gh is not logged in. Run: gh auth login   then re-run."; exit 1
fi
ok "gh is installed and logged in as $(gh api user --jq .login)"
if ! gh auth status 2>&1 | grep -iqE "scopes:.*(^|[ ,'])project\b"; then
  warn "your gh token doesn't show the 'project' scope, which gh project commands need."
  say "Run this in another terminal (it opens a browser), then come back:"
  say "    gh auth refresh -s project"
  pause "Press Enter once the scope has been added"
fi
if ! PROJECT_TITLE=$(gh project view "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json --jq .title 2>/dev/null); then
  fail "can't read Project #${PROJECT_NUMBER} owned by ${PROJECT_OWNER}."
  say "Check the 'project' scope (gh auth refresh -s project) and that this account"
  say "has write access to ${PROJECT_URL}."; exit 1
fi
ok "Project #${PROJECT_NUMBER} is reachable: \"${PROJECT_TITLE}\""
note "Nothing on the Project or the repo has been changed yet."
pause

# ── 2. Import existing issues ─────────────────────────────────────────────
stage "Import existing issues (open + closed, no pull requests)"
say "Every issue in ${REPO} that isn't in the Project yet gets added."
say "Issues already there are skipped, so nothing is duplicated. The issues"
say "themselves are not edited: adding to a Project is a Project-side link."
ISSUE_ROWS=$(repo_issues)
IN_PROJECT=$(project_issue_numbers)
TO_ADD=""
while IFS= read -r row; do
  [[ -z "$row" ]] && continue
  n=${row%% *}
  has_line "$n" "$IN_PROJECT" || TO_ADD+="${n}
"
done <<<"$ISSUE_ROWS"
N_ISSUES=$(count_lines <<<"$ISSUE_ROWS"); N_ADD=$(count_lines <<<"$TO_ADD")
say "Repo issues: ${N_ISSUES}   already in Project: $(( N_ISSUES - N_ADD ))   to add: ${N_ADD}"
if (( N_ADD == 0 )); then
  ok "all issues are already in the Project"
elif confirm "Add these ${N_ADD} issue(s) to the Project now?"; then
  while IFS= read -r n; do
    [[ -z "$n" ]] && continue
    if gh project item-add "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" \
         --url "https://github.com/${REPO}/issues/${n}" >/dev/null 2>&1; then
      ok "added #${n}"
    else
      fail "could not add #${n}"; SKIPPED+=("add issue #${n} to the Project")
    fi
  done <<<"$TO_ADD"
else
  SKIPPED+=("import existing issues (stage 2 declined)")
fi
pause

# ── 3. Status options ─────────────────────────────────────────────────────
stage "Status field: Todo · In Progress · Review · Done"
say "GitHub creates Status with Todo, In Progress and Done. Sprint needs a"
say "Review column too. Adding an option through the API can reshuffle the"
say "existing ones, so this step is done in the browser and verified here."
MISSING=$(missing_status_options)
if [[ -z "$MISSING" ]]; then
  ok "Status already has: $(status_options | join_lines ', ')"
else
  say "Missing option(s): $(join_lines ', ' <<<"$MISSING")"
  open_url "${PROJECT_URL}/settings"
  step "In the left sidebar under Fields, click 'Status'."
  step "Under Options, click 'Add option', type each missing name exactly as"
  step "shown above (case matters), and drag it into place so the order reads:"
  step "Todo → In Progress → Review → Done. Don't rename or delete the others."
  step "Click 'Save options'."
  while :; do
    pause "Press Enter when the options are saved (I'll re-check)"
    MISSING=$(missing_status_options)
    [[ -z "$MISSING" ]] && break
    warn "still missing: $(join_lines ', ' <<<"$MISSING")"
  done
  ok "Status now has: $(status_options | join_lines ', ')"
fi
pause

# ── 4. Sprint board view ──────────────────────────────────────────────────
stage "Create the '${SPRINT_VIEW}' Board view grouped by Status"
LAYOUT=$(sprint_view_layout)
if [[ "$LAYOUT" == "BOARD_LAYOUT" ]]; then
  ok "a Board view named '${SPRINT_VIEW}' already exists"
else
  [[ -n "$LAYOUT" ]] && warn "a view named '${SPRINT_VIEW}' exists but its layout is ${LAYOUT}, not Board"
  open_url "$PROJECT_URL"
  step "Click 'New view' (the + tab to the right of the existing view tabs)."
  step "Open the new tab's ▾ menu → 'Rename view' → type  ${SPRINT_VIEW}  → Enter."
  step "Same ▾ menu → under 'Layout' pick 'Board'."
  step "Same ▾ menu → 'Column by' (older UI: 'Column field') → choose 'Status'."
  step "Same ▾ menu → 'Save changes'. Leave the filter empty so closed issues stay visible."
  while :; do
    pause "Press Enter when the view is saved (I'll re-check)"
    [[ "$(sprint_view_layout)" == "BOARD_LAYOUT" ]] && break
    warn "no saved Board view named '${SPRINT_VIEW}' yet"
  done
  ok "'${SPRINT_VIEW}' Board view found"
fi
COLUMN_FIELD=$(sprint_view_column_field)
if [[ "$COLUMN_FIELD" == "Status" ]]; then
  ok "its columns are grouped by Status"
elif [[ -n "$COLUMN_FIELD" ]]; then
  warn "its column field is '${COLUMN_FIELD}', expected Status. Fix it via the view's ▾ menu → 'Column by'."
  pause "Press Enter once corrected"
else
  note "the API didn't report the column field, so confirm it by eye:"
  confirm "Does the Sprint board show columns Todo / In Progress / Review / Done?" \
    || SKIPPED+=("set the Sprint view's 'Column by' to Status")
fi
pause

# ── 5. Auto-add workflow ──────────────────────────────────────────────────
stage "Turn on 'Auto-add to project' for ${REPO} with filter  is:issue"
say "This makes every future issue in the repo (Wayfinder maps, tickets, or"
say "anything else) appear in the Project automatically. Nothing about how"
say "Wayfinder creates or labels issues changes."
if [[ "$(workflow_state 'Auto-add to project')" == "true" ]]; then
  ok "'Auto-add to project' is already enabled"
  note "double-check its filter in the browser if you didn't set it yourself:"
  note "  ${PROJECT_URL}/workflows"
else
  open_url "${PROJECT_URL}/workflows"
  step "Under 'Default workflows', click 'Auto-add to project'."
  step "Click 'Edit' (top right)."
  step "Under 'Filters', choose the repository  ${REPO}."
  step "In the filter box next to it, replace the default with exactly:  is:issue"
  step "Click 'Save and turn on workflow'."
  note "GitHub only auto-adds items created or updated after this point; stage 2 covered the backlog."
  wait_until_workflow "Auto-add to project" true
  ok "'Auto-add to project' enabled"
fi
pause

# ── 6. Other default workflows ────────────────────────────────────────────
stage "Keep completed work visible; don't let Status drive issue state"
say "Two checks on the same Workflows page, nothing to enable:"
open_url "${PROJECT_URL}/workflows"
case "$(workflow_state 'Auto-archive items')" in
  true)
    warn "'Auto-archive items' is ON. Closed issues would vanish from views."
    step "Click 'Auto-archive items' → toggle it Off (or Edit → 'Disable workflow')."
    wait_until_workflow "Auto-archive items" false
    ok "'Auto-archive items' is now off" ;;
  false)
    ok "'Auto-archive items' is off, so closed issues stay in the Project" ;;
  *)
    step "Confirm 'Auto-archive items' shows as Off."
    confirm "Is 'Auto-archive items' Off?" || SKIPPED+=("turn off 'Auto-archive items'") ;;
esac
say ""
say "Leave these exactly as GitHub ships them (nothing to click):"
note "  • 'Item closed' → Status: Done        stays ON (a closed issue lands in Done)"
note "  • 'Item added to project' → Todo     default ON, fine as is"
note "  • 'Pull request merged'              irrelevant, PRs aren't imported"
note "  • 'Auto-close issue' (Status → close) must stay OFF: Wayfinder owns"
note "    closing issues, so the board must never close or reopen them."
case "$(workflow_state 'Auto-close issue')" in
  true)
    warn "'Auto-close issue' is ON. Turn it Off so moving a card can't close an issue."
    wait_until_workflow "Auto-close issue" false
    ok "'Auto-close issue' is off" ;;
  false)
    ok "'Auto-close issue' is off" ;;
  *)
    confirm "Is 'Auto-close issue' Off?" || SKIPPED+=("turn off 'Auto-close issue'") ;;
esac
pause

# ── 7. Verification ───────────────────────────────────────────────────────
stage "Verification"
ISSUE_ROWS=$(repo_issues)
IN_PROJECT=$(project_issue_numbers)
OPEN_IN=0; CLOSED_IN=0; MISSING_ISSUES=""
while IFS= read -r row; do
  [[ -z "$row" ]] && continue
  n=${row%% *}; s=${row#* }
  if has_line "$n" "$IN_PROJECT"; then
    if [[ "$s" == "OPEN" ]]; then OPEN_IN=$((OPEN_IN + 1)); else CLOSED_IN=$((CLOSED_IN + 1)); fi
  else
    MISSING_ISSUES+="#${n} "
  fi
done <<<"$ISSUE_ROWS"
N_ISSUES=$(count_lines <<<"$ISSUE_ROWS")
if [[ -z "$MISSING_ISSUES" ]]; then
  ok "all ${N_ISSUES} repo issues are in the Project (${OPEN_IN} open, ${CLOSED_IN} closed)"
else
  fail "issues not in the Project: ${MISSING_ISSUES}"; SKIPPED+=("import ${MISSING_ISSUES}")
fi
if (( OPEN_IN > 0 && CLOSED_IN > 0 )); then
  ok "both open and closed issues are represented"
else
  warn "open=${OPEN_IN} closed=${CLOSED_IN}: one state has no items yet"
fi
PRS=$(project_pr_count)
if [[ "$PRS" == "0" ]]; then
  ok "no pull requests were imported"
else
  note "the Project holds ${PRS} pull request item(s); this wizard added none"
fi
MISSING=$(missing_status_options)
if [[ -z "$MISSING" ]]; then
  ok "Status options: $(status_options | join_lines ' → ')"
else
  fail "Status is missing: $(join_lines ', ' <<<"$MISSING")"
fi
if [[ "$(sprint_view_layout)" == "BOARD_LAYOUT" ]]; then
  ok "'${SPRINT_VIEW}' Board view exists"
else
  fail "'${SPRINT_VIEW}' Board view not found"
fi
COLUMN_FIELD=$(sprint_view_column_field)
case "$COLUMN_FIELD" in
  Status) ok "'${SPRINT_VIEW}' is grouped by Status" ;;
  "")     note "'${SPRINT_VIEW}' column field: not reported by the API (checked by eye in stage 4)" ;;
  *)      fail "'${SPRINT_VIEW}' column field is ${COLUMN_FIELD}, not Status" ;;
esac
case "$(workflow_state 'Auto-add to project')" in
  true)  ok "'Auto-add to project' is on (filter is:issue, set in stage 5)" ;;
  false) fail "'Auto-add to project' is off" ;;
  *)     note "'Auto-add to project': not reported by the API (checked by eye in stage 5)" ;;
esac
case "$(workflow_state 'Auto-archive items')" in
  false) ok "'Auto-archive items' is off" ;;
  true)  fail "'Auto-archive items' is on" ;;
  *)     note "'Auto-archive items': not reported by the API (checked by eye in stage 6)" ;;
esac
say ""
note "Untouched by design: Wayfinder labels, sub-issue links, issue dependencies,"
note "issue bodies, branches, code. No GitHub Actions were created."
note "Project: ${PROJECT_URL}"
pause "Press Enter to finish"

finish
